### ISSUE TITLE
Insomnia upload all workspaces every time

### ISSUE THREAD

**Issue by cxolast** [PoOwAa/insomnia-plugin-snippet-sync#16]
Current behavior:
When i try upload one workspace, uploaded all workspaces every time.
Checked on insomnia on mac and windows.
![Screenshot_1](https://user-images.githubusercontent.com/13518938/101353211-48acac80-38a4-11eb-9484-2a58df59ddd2.png)

Expected behavior:
Upload one(current) workspace

**Comment by PoOwAa** [comment]
Thanks for the bug report! Solved in latest version, maybe insomnia needs some time, to update the plugin from NPM
